import mocha from "mocha";
import { expect } from "chai";
import {
  Amenities,
  ArticleAuthor,
  Availability,
  BookmarkButton,
  Breadcrumbs,
  Bullet,
  Button,
  Calendar,
  Callout,
  ContentBlock,
  ContentHeader,
  ContentSectionList,
  DotLoader,
  Dropdown,
  EditLink,
  ExpandButton,
  Flyout,
  Checkbox,
  DateRange,
  Input,
  InputGroup,
  Label,
  NumberInput,
  Range,
  Select,
  Textarea,
  Heading,
  Icon,
  IconButton,
  ImageCarousel,
  ImageGallery,
  ImageHero,
  LastUpdated,
  Lede,
  // ListItem,
  // ListItemBookable,
  Loading,
  MapMarker,
  MoreLink,
  Narrative,
  NumberList,
  NumberMarker,
  Overlay,
  PageHeader,
  PaginatorButton,
  Placeholder,
  PoiPaginator,
  Price,
  ProviderLogo,
  Rating,
  RelatedTour,
  ReviewedBadge,
  ShareMenu,
  SidebarSection,
  StaticMap,
  Strapline,
  Tag,
  TagList,
  Takeover,
  Toolbar,
  Tooltip,
} from "../src";

describe("backpack-ui", () => {
  it("should have all the exports", () => {
    expect(Amenities).to.be.ok;
    expect(ArticleAuthor).to.be.ok;
    expect(Availability).to.be.ok;
    expect(BookmarkButton).to.be.ok;
    expect(Breadcrumbs).to.be.ok;
    expect(Button).to.be.ok;
    expect(Bullet).to.be.ok;
    expect(Calendar).to.be.ok;
    expect(Callout).to.be.ok;
    expect(ContentBlock).to.be.ok;
    expect(ContentHeader).to.be.ok;
    expect(ContentSectionList).to.be.ok;
    expect(DotLoader).to.be.ok;
    expect(Dropdown).to.be.ok;
    expect(EditLink).to.be.ok;
    expect(ExpandButton).to.be.ok;
    expect(Flyout).to.be.ok;
    expect(Checkbox).to.be.ok;
    expect(DateRange).to.be.ok;
    expect(Input).to.be.ok;
    expect(InputGroup).to.be.ok;
    expect(Label).to.be.ok;
    expect(NumberInput).to.be.ok;
    expect(Range).to.be.ok;
    expect(Select).to.be.ok;
    expect(Textarea).to.be.ok;
    expect(Heading).to.be.ok;
    expect(Icon).to.be.ok;
    expect(IconButton).to.be.ok;
    expect(ImageCarousel).to.be.ok;
    expect(ImageGallery).to.be.ok;
    expect(ImageHero).to.be.ok;
    expect(LastUpdated).to.be.ok;
    expect(Lede).to.be.ok;
    // expect(ListItem).to.be.ok;
    // expect(ListItemBookable).to.be.ok;
    expect(Loading).to.be.ok;
    expect(MapMarker).to.be.ok;
    expect(MoreLink).to.be.ok;
    expect(Narrative).to.be.ok;
    expect(NumberList).to.be.ok;
    expect(NumberMarker).to.be.ok;
    expect(Overlay).to.be.ok;
    expect(PageHeader).to.be.ok;
    expect(PaginatorButton).to.be.ok;
    expect(Placeholder).to.be.ok;
    expect(PoiPaginator).to.be.ok;
    expect(Price).to.be.ok;
    expect(ProviderLogo).to.be.ok;
    expect(Rating).to.be.ok;
    expect(RelatedTour).to.be.ok;
    expect(ReviewedBadge).to.be.ok;
    expect(ShareMenu).to.be.ok;
    expect(SidebarSection).to.be.ok;
    expect(StaticMap).to.be.ok;
    expect(Strapline).to.be.ok;
    expect(Tag).to.be.ok;
    expect(TagList).to.be.ok;
    expect(Takeover).to.be.ok;
    expect(Toolbar).to.be.ok;
    expect(Tooltip).to.be.ok;
  });
});
