import mocha from "mocha";
import { expect } from "chai";
import { Amenities } from "../src";
import { Availability } from "../src";
import { Bookmark } from "../src";
import { Breadcrumbs } from "../src";
import { Bullet } from "../src";
import { Button } from "../src";
import { Calendar } from "../src";
import { Callout } from "../src";
import { ContentBlock } from "../src";
import { ContentHeader } from "../src";
import { ContentSectionList } from "../src";
import { DotLoader } from "../src";
import { Dropdown } from "../src";
import { EditLink } from "../src";
import { ExpandButton } from "../src";
import { Flyout } from "../src";
import { Checkbox } from "../src";
import { DateRange } from "../src";
import { Input } from "../src";
import { InputGroup } from "../src";
import { Label } from "../src";
import { NumberInput } from "../src";
import { Range } from "../src";
import { Select } from "../src";
import { Textarea } from "../src";
import { Heading } from "../src";
import { Icon } from "../src";
import { IconButton } from "../src";
import { ImageCarousel } from "../src";
import { ImageGallery } from "../src";
import { ImageHero } from "../src";
import { ImagesContainer } from "../src";
import { LastUpdated } from "../src";
import { Lede } from "../src";
// import { ListItem } from "../src";
// import { ListItemBookable } from "../src";
import { Loading } from "../src";
import { MapMarker } from "../src";
import { MoreLink } from "../src";
import { Narrative } from "../src";
import { NumberList } from "../src";
import { NumberMarker } from "../src";
import { Overlay } from "../src";
import { PageHeader } from "../src";
import { PaginatorButton } from "../src";
import { Placeholder } from "../src";
import { PoiPaginator } from "../src";
import { Price } from "../src";
import { Profile } from "../src";
import { ProviderLogo } from "../src";
import { Rating } from "../src";
import { RelatedTour } from "../src";
import { ReviewedBadge } from "../src";
import { ShareMenu } from "../src";
import { SidebarSection } from "../src";
import { StaticMap } from "../src";
import { Strapline } from "../src";
import { Tag } from "../src";
import { TagList } from "../src";
import { Takeover } from "../src";
import { Toolbar } from "../src";
import { Tooltip } from "../src";

describe("backpack-ui", () => {
  it("should have all the exports", () => {
    expect(Amenities).to.be.ok;
    expect(Availability).to.be.ok;
    expect(Bookmark).to.be.ok;
    expect(Breadcrumbs).to.be.ok;
    expect(Button).to.be.ok;
    expect(Bullet).to.be.ok;
    expect(Calendar).to.be.ok;
    expect(Callout).to.be.ok;
    expect(ContentBlock).to.be.ok;
    expect(ContentHeader).to.be.ok;
    expect(ContentSectionList).to.be.ok;
    expect(DotLoader).to.be.ok;
    expect(Dropdown).to.be.ok;
    expect(EditLink).to.be.ok;
    expect(ExpandButton).to.be.ok;
    expect(Flyout).to.be.ok;
    expect(Checkbox).to.be.ok;
    expect(DateRange).to.be.ok;
    expect(Input).to.be.ok;
    expect(InputGroup).to.be.ok;
    expect(Label).to.be.ok;
    expect(NumberInput).to.be.ok;
    expect(Range).to.be.ok;
    expect(Select).to.be.ok;
    expect(Textarea).to.be.ok;
    expect(Heading).to.be.ok;
    expect(Icon).to.be.ok;
    expect(IconButton).to.be.ok;
    expect(ImageCarousel).to.be.ok;
    expect(ImageGallery).to.be.ok;
    expect(ImageHero).to.be.ok;
    expect(ImagesContainer).to.be.ok;
    expect(LastUpdated).to.be.ok;
    expect(Lede).to.be.ok;
    // expect(ListItem).to.be.ok;
    // expect(ListItemBookable).to.be.ok;
    expect(Loading).to.be.ok;
    expect(MapMarker).to.be.ok;
    expect(MoreLink).to.be.ok;
    expect(Narrative).to.be.ok;
    expect(NumberList).to.be.ok;
    expect(NumberMarker).to.be.ok;
    expect(Overlay).to.be.ok;
    expect(PageHeader).to.be.ok;
    expect(PaginatorButton).to.be.ok;
    expect(Placeholder).to.be.ok;
    expect(PoiPaginator).to.be.ok;
    expect(Price).to.be.ok;
    expect(Profile).to.be.ok;
    expect(ProviderLogo).to.be.ok;
    expect(Rating).to.be.ok;
    expect(RelatedTour).to.be.ok;
    expect(ReviewedBadge).to.be.ok;
    expect(ShareMenu).to.be.ok;
    expect(SidebarSection).to.be.ok;
    expect(StaticMap).to.be.ok;
    expect(Strapline).to.be.ok;
    expect(Tag).to.be.ok;
    expect(TagList).to.be.ok;
    expect(Takeover).to.be.ok;
    expect(Toolbar).to.be.ok;
    expect(Tooltip).to.be.ok;
  });
});